defaults:
  - lang_default.yaml

_target_: salad.models.language_phase2.LangPhase2Model
network:
  _target_: salad.model_components.network.CondDiffNetwork
  input_dim: 512
  residual: true
  context_dim: 784 # concat of 768 lang feat and gaussian.
  context_embedding_dim: 1024
  embedding_dim: 512
  encoder_use_time: false
  encoder_type: transformer
  decoder_type: transformer_encoder
  enc_num_layers: 6
  dec_num_layers: 6
  use_timestep_embedder: true
  timestep_embedder_dim: 128

dataset_kwargs:
  data_keys: ["s_j_affine", "g_js_affine"]
