defaults:
- default.yaml

_target_: salad.models.phase1.Phase1Model

network:
  _target_: salad.model_components.network.UnCondDiffNetwork
  input_dim: 16
  embedding_dim: 512
  num_heads: 4
  use_timestep_embedder: true
  timestep_embedder_dim: 128
  enc_num_layers: 6
  residual: true
  encoder_type: transformer
  attn_dropout: 0.0

global_normalization: partial # normalize pi, eigenvalues.

dataset_kwargs:
  data_keys: ["g_js_affine"]
  global_normalization: ${model.global_normalization}
